worktree-path = "{{ repo_path }}/.worktrees/{{ repo }}.{{ branch | sanitize }}"

[aliases]
"-" = "wt switch -"
"^" = "wt switch {{ primary_worktree_path }} {{ args }}"
cb = "wt switch --create {{ args }}"
co = "wt switch {{ args }}"
ls = "wt list {{ args }}"
q = "wt switch {{ primary_worktree_path }} {{ args }}"
rm = "wt remove {{ args }}"
