[tools."github:Yubico/yubioath-flutter"]
bin_path = "."
filter_bins = "yubioath"
os = "linux"
postinstall = "{{ config_source | canonicalize | dirname | dirname }}/hooks/postinstall-github-Yubico-yubioath-flutter"
rename_exe = { "authenticator" = "yubioath" }
strip_components = 1
version = "latest"
