#!/bin/sh
[ -z "${DEST}" ] || [ ! -d "${DEST}" ] && exit 1
if [ ! -d "${DEST}/.ssh" ]; then
    mkdir -p "${DEST}/.ssh"
    chmod 0700 "${DEST}/.ssh"
fi
if [ -f "${DEST}/.ssh/config" ]; then
    cp -a "${DEST}/.ssh/config" "${DEST}/.ssh/config.dotfiles_backup"
    sed -i "${DEST}/.ssh/config" \
        -e '/### DOTFILES AUTO CONFIG/,/### END DOTFILES AUTO CONFIG/d'
    if [ "$(tail -n1 "${DEST}/.ssh/config")" != "" ]; then
        echo >> "${DEST}/.ssh/config"
    fi
fi
cat config_append >> "${DEST}/.ssh/config"
chmod 0600 "${DEST}/.ssh/config"
