#!/bin/sh
[ -z "${DEST}" -o ! -d "${DEST}" ] && exit 1
if [ ! -d "${DEST}/.ssh" ]; then
    mkdir -p "${DEST}/.ssh"
    chmod 700 "${DEST}/.ssh"
fi
if [ -f "${DEST}/.ssh/config" ]; then
    cp "${DEST}/.ssh/config" "${DEST}/.ssh/config.dotfiles_backup"
    sed -i "${DEST}/.ssh/config" -e '/### DOTFILES AUTO CONFIG/,$d'
fi
cat config_append >> "${DEST}/.ssh/config"
