name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v7

      - name: 🍳 Set up repository
        uses: ./.github/actions/setup

      - name: 🪝 Cache pre-commit hooks
        uses: actions/cache@v6
        with:
          path: ~/.cache/prek
          key: "prek-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}"

      - name: 📐 Lint
        run: prek run --all-files

  betterleaks:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 🍳 Set up repository
        uses: ./.github/actions/setup

      - name: 🔍 Check for secrets
        run: mise run dotfiles:betterleaks:scan

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
