[tools]
node = "latest"
"pipx:ansible-lint" = "latest"
"pipx:bdbox" = "latest"
"pipx:easyeda2kicad" = "latest"
"pipx:linode-cli" = "latest"
"pipx:mdv" = "latest"
"pipx:mpremote" = "latest"
"pipx:platformio" = "latest"
"pipx:pre-commit" = "latest"
"pipx:ruff" = "latest"
"pipx:s3cmd" = "latest"
"pipx:scons" = "latest"
"pipx:ty" = "latest"
"pipx:yt-dlp" = "latest"
uv = "latest"
worktrunk = "latest"
